### ISSUE TITLE
Learning/testing the framework: Where is 'sydr.zip'?

### ISSUE THREAD

**Issue by program-learner-1** [ispras/oss-sydr-fuzz#118]
To learn and test your framework, I see that it is necessary to have the archive file `sydr.zip`.
Where can I find it?

```
## Run Hybrid Fuzzing

Unzip Sydr (`sydr.zip`) in `projects/XXX` directory:

    $ unzip sydr.zip
```

**Comment by SweetVishnya** [comment]
[Sydr-Fuzz](https://sydr-fuzz.github.io/) is a proprietary software. However, you may fuzz directly via libFuzzer or AFL++ (arguments are listed in TOML files). Also, crash triaging tool [Casr](https://github.com/ispras/casr) is open source.

**Comment by program-learner-1** [comment]
It `Sydr-Fuzz` the result of academic research?

**Comment by SweetVishnya** [comment]
Yeah, it has a dedicated [paper](https://arxiv.org/abs/2211.11595), [demo](https://vishnya.xyz/vishnyakov-isprasopen2022.webm), and [slides](https://vishnya.xyz/vishnyakov-isprasopen2022.pdf).

**Comment by program-learner-1** [comment]
> Yeah, it has a dedicated paper, demo and slides.

So why is it proprietary software and not open source software?

This prevents it from being studied and possibly improved.

**Comment by SweetVishnya** [comment]
Because it is distributed via commercial license. However, you may still use `casr-afl` that is open source.

**Comment by program-learner-1** [comment]
First draft of the UNESCO Recommendation on Open Science

[...]

9. For the purposes of this Recommendation, 'Open Science' means a complex of at
least the following key elements:

[...]

(iii) Open Source/Software and Open Hardware: open software describes software
that is publicly available under an open license that grants others the right to
access, modify, expand, study, create derivative works, use and/or share the
software and its source code, design, or blueprint. The source code must be
included in the software release or made available upon request and the chosen
license must allow modifications, derived works, and sharing under equal
conditions. [...]

(https://unesdoc.unesco.org/ark:/48223/pf0000374837)
