### ISSUE TITLE
[openssl] harness for sydr with memory leak

### ISSUE THREAD

**Issue by acr0niks** [ispras/oss-sydr-fuzz#175]
Hi! 

I used sydr for fuzzing openssl and discovered that all sydr harnesses lack memory freeing.
This results in a memory leak.
For example, corrected asn1_sydr.c main function looks like this:

```c
int main(int argc, char** argv)
{
  FuzzerInitialize(&argc, &argv);
  FILE* fd = fopen(argv[1], "rb");
  if (!fd) return 1;
  fseek(fd, 0, SEEK_END);
  long fsize = ftell(fd);
  fseek(fd, 0, SEEK_SET);
  char* buffer = (char*)malloc(fsize);
  fread(buffer, 1, fsize, fd);
  fclose(fd);
  int ret = FuzzerTestOneInput((const uint8_t*)buffer, fsize);
  free(buffer); // need to prevent memory leak;
  FuzzerCleanup();
  return ret;
}
```
I can make a pull request with fixes to openssl, but there are similar cases in other projects.
Do I need to make a pull request with fixes?

**Comment by SweetVishnya** [comment]
Sure, all PRs are welcomed :)

**Comment by acr0niks** [comment]
ok, i'll do it :)
