### ISSUE TITLE
Where is the “sydr.zip”

### ISSUE THREAD

**Issue by gtt1995** [ispras/oss-sydr-fuzz#237]
Hello,
   I am very excited to sydr project, but i don`t find the sydr.zip from /projects/project/README.

**Comment by gtt1995** [comment]
@apach301

**Comment by apach301** [comment]
Hi! Sydr is a commercial product with no source code available. This repository only contains data to build fuzzing targets for various open source projects.

**Comment by gtt1995** [comment]
thanks your reply, how can i purchase it?

**Comment by apach301** [comment]
Sales and trial versions are only possible for companies and institutes. To request a product or for additional info use mail sdl@ispras.ru

**Comment by gtt1995** [comment]
Thanks！
